version: 2.1

jobs:
  build:
    docker:
      - image: node:latest
    steps:
      - run: npm run test

workflows:
  version: 2
  test_workflow:
    jobs:
      - build:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
